In [2]:
import pandas as pd

In [6]:
athletes = pd.read_csv('../data/summerOly_athletes.csv')

In [8]:
df_before_2024 = athletes[athletes['Year'] < 2024]

In [10]:
df_before_2024

,Name,Sex,Team,NOC,Year,City,Sport,Event,Medal
0,A Dijiang,M,China,CHN,1992,Barcelona,Basketball,Basketball Men's Basketball,No medal
1,A Lamusi,M,China,CHN,2012,London,Judo,Judo Men's Extra-Lightweight,No medal
2,Gunnar Aaby,M,Denmark,DEN,1920,Antwerpen,Football,Football Men's Football,No medal
3,Edgar Aabye,M,Denmark/Sweden,DEN,1900,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,Cornelia (-strannood),F,Netherlands,NED,1932,Los Angeles,Athletics,Athletics Women's 100 metres,No medal
...,...,...,...,...,...,...,...,...,...
237668,Klaudia Zwolinska,F,Poland,POL,2020,Tokyo,Canoe Slalom,Women's Kayak,No medal
237669,Yulia Zykova,F,Russia,ROC,2020,Tokyo,Shooting,50m Rifle 3 Positions Women,Silver
237670,Ekaterina Zyuzina,F,Russia,ROC,2020,Tokyo,Sailing,Women's One Person Dinghy - Laser Radial,No medal
237671,Sylwia Zyzanska,F,Poland,POL,2020,Tokyo,Archery,Women's Individual,No medal
237672,Sylwia Zyzanska,F,Poland,POL,2020,Tokyo,Archery,Mixed Team,No medal

In [12]:
nocs_no_medals = df_before_2024.groupby('NOC').filter(lambda group: (group['Medal'] == "No medal").all())

In [14]:
nocs_no_medals

,Name,Sex,Team,NOC,Year,City,Sport,Event,Medal
98,M'Bairo Abakar,M,Chad,CHA,1992,Barcelona,Judo,Judo Men's Half-Middleweight,No medal
141,Carlos Balladares,M,Nicaragua,NCA,2004,Athina,Athletics,Athletics Men's 100 metres,No medal
142,Carlos Abaunza,M,Nicaragua,NCA,1976,Montreal,Athletics,Athletics Men's High Jump,No medal
153,Gana Kimet,M,Chad,CHA,1972,Munich,Athletics,Athletics Men's 100 metres,No medal
298,Moustafa Naser,M,Libya,LBA,1996,Atlanta,Athletics,Athletics Men's 400 metres,No medal
...,...,...,...,...,...,...,...,...,...
237379,Robyn Young,F,Eswatini,SWZ,2020,Tokyo,Swimming,Women's 50m Freestyle,No medal
237421,Naomie Yumba,F,Democratic Republic of the Congo,COD,2020,Tokyo,Boxing,Women's Light (57-60kg),No medal
237468,Yasmin Zammit,F,Malta,MLT,2020,Tokyo,Weightlifting,Women's 64kg,No medal
237486,Ivan Zarco,M,Honduras,HON,2020,Tokyo,Athletics,Men's Marathon,No medal
237519,Jean-luc Zephir,M,Saint Lucia,LCA,2020,Tokyo,Swimming,Men's 100m Freestyle,No medal

In [26]:
len(nocs_no_medals['Team'].unique())

94

In [28]:
nocs_no_medals_after_2024 = athletes.groupby('NOC').filter(lambda group: (group['Medal'] == "No medal").all())

In [30]:
len(nocs_no_medals_after_2024['Team'].unique())

101